{% set version = "1.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sessioninfo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sessioninfo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sessioninfo/sessioninfo_{{ version }}.tar.gz
  sha256: f56283857c53ac8691e3747ed48fe03e893d8ff348235bff7364658bcfb0c7cb

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-cli
    - r-withr
  run:
    - r-base
    - r-cli
    - r-withr

test:
  commands:
    - $R -e "library('sessioninfo')"           # [not win]
    - "\"%R%\" -e \"library('sessioninfo')\""  # [win]

about:
  home: https://github.com/r-lib/sessioninfo#readme
  license: GPL-2.0-only
  summary: Query and print information about the current R session. It is similar to 'utils::sessionInfo()', but includes more information about packages, and where they were installed from.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - roryk

# Package: sessioninfo
# Title: R Session Information
# Version: 1.1.1
# Author: Gabor Csardi, R core, Hadley Wickham, Winston Chang, Robert M Flight, Kirill Muller, Jim Hester
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Description: Query and print information about the current R session. It is similar to 'utils::sessionInfo()', but includes more information about packages, and where they were installed from.
# License: GPL-2
# LazyData: true
# URL: https://github.com/r-lib/sessioninfo#readme
# BugReports: https://github.com/r-lib/sessioninfo/issues
# RoxygenNote: 6.1.0
# Suggests: callr, covr, mockery, testthat
# Imports: cli, tools, utils, withr
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2018-11-05 16:32:45 UTC; gaborcsardi
# Repository: CRAN
# Date/Publication: 2018-11-05 17:20:02 UTC
